(function(){function f(a){return function(){return this[a]}}var k,l=this;function aa(){}
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=m(a);return"array"==b||"object"==b&&"number"==typeof a.length}function n(a){return"string"==typeof a}function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function p(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return p.apply(null,arguments)}
function q(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}function ea(a,b){function c(){}c.prototype=b.prototype;a.Ja=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.La=function(a,c,g){var h=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,h)}};var u;function v(a,b,c,d,e){this.Q=a;this.d=b;this.P=c;this.sa=d;this.q=e}v.prototype.getName=f("d");
function fa(a){var b=[a.Q?x(a.Q)+".":"",a.d?x(u?u(a.d):a.d):"anonymous",x(a.sa),a.P?" [as "+x(u?u(a.P):a.P)+"]":""];if(a.q)if(b.push(" at "),Boolean(l.CLOSURE_INSPECTOR___&&l.CLOSURE_INSPECTOR___.supportsJSUnit)){var c=a.q.match(/\d+$/)[0];b.push('\x3ca href\x3d"" onclick\x3d"CLOSURE_INSPECTOR___.showLine(\'',x(a.q),"', '",c,"'); return false\"\x3e",x(a.q),"\x3c/a\x3e")}else b.push(x(a.q));return b.join("")}
var ga=RegExp("^    at(?: (?:(.*?)\\.)?((?:new )?(?:[a-zA-Z_$][\\w$]*|\x3canonymous\x3e))(?: \\[as ([a-zA-Z_$][\\w$]*)\\])?)? (?:\\(unknown source\\)|\\(native\\)|\\((?:eval at )?((?:http|https|file)://[^\\s)]+|javascript:.*)\\)|((?:http|https|file)://[^\\s)]+|javascript:.*))$"),ha=/^([a-zA-Z_$][\w$]*)?(\(.*\))?@(?::0|((?:http|https|file):\/\/[^\s)]+|javascript:.*))$/,ia=RegExp("^(?:(?:([a-zA-Z_$][\\w$]*)|\x3canonymous function(?:\\: (?:([a-zA-Z_$][\\w$]*(?:\\.[a-zA-Z_$][\\w$]*)*)\\.)?([a-zA-Z_$][\\w$]*))?\x3e)(\\(.*\\)))?@((?:http|https|file)://[^\\s)]+|javascript:.*)?$"),
ja=/^function ([a-zA-Z_$][\w$]*)/,ka=RegExp("^   at ([a-zA-Z_$][\\w$]*(?:\\s+\\w+)*)\\s*\\((eval code:[^)]*|((?:http|https|file)://[^\\s)]+|javascript:.*))\\)?$");
function la(){for(var a=[],b=arguments.callee.caller,c=0;b&&20>c;){var d=Function.prototype.toString.call(b).match(ja),d=d?d[1]:"",e=["("];if(b.arguments)for(var g=0;g<b.arguments.length;g++){var h=b.arguments[g];0<g&&e.push(", ");n(h)?e.push('"',h,'"'):h&&h.$replay?e.push("goog.testing.Mock"):e.push(String(h))}else e.push("unknown");e.push(")");a.push(new v("",d,"",e.join(""),""));try{b=b.caller}catch(r){break}c++}return a}
function ma(a){var b=a.match(ga);if(b)return new v(b[1]||"",b[2]||"",b[3]||"","",b[4]||b[5]||"");if(5E5<a.length){var b=a.indexOf("("),c=a.lastIndexOf("@"),d=a.lastIndexOf(":"),e="";0<=b&&b<c&&(e=a.substring(0,b));var g="";0<=c&&c+1<d&&(g=a.substring(c+1));d="";0<=b&&0<c&&b<c&&(d=a.substring(b,c));return new v("",e,"",d,g)}return(b=a.match(ha))?new v("",b[1]||"","",b[2]||"",b[3]||""):(b=a.match(ia))?new v(b[2]||"",b[1]||b[3]||"","",b[4]||"",b[5]||""):(b=a.match(ka))?new v("",b[1]||"","","",b[2]||
""):null}function x(a){return a.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;")}function na(a){for(var b=a.length-1;a[b]&&(!a[b].d||"[object Object]"==a[b].Q);)b--;for(var c=-1,d=0;d<a.length;d++)if(a[d]&&"_assert"==a[d].getName()){c=d;break}for(var e=[],d=c+1;d<=b;d++)e.push("\x3e "),a[d]?e.push(fa(a[d])):e.push("(unknown)"),e.push("\n");return e.join("")}
function oa(a){a=a.replace(/\s*$/,"").split("\n");for(var b=[],c=0;c<a.length;c++)b.push(ma(a[c]));return b}function pa(){var a=Error();if(a.stack)return a.stack;try{null.x()}catch(b){return b.stack}return""}q("setDeobfuscateFunctionName",function(a){u=a});function z(a,b){return a==b}function qa(a,b){return a.toString()===b.toString()}var ra={String:z,Number:z,Boolean:z,Date:function(a,b){return a.getTime()==b.getTime()},RegExp:qa,Function:qa};function sa(a,b,c){return Math.abs(a-b)<=c}var ta={Number:sa};
function A(a){var b=typeof a;try{switch(b){case "object":if(null==a){b="null";break}case "function":switch(a.constructor){case (new String("")).constructor:b="String";break;case (new Boolean(!0)).constructor:b="Boolean";break;case (new Number(0)).constructor:b="Number";break;case [].constructor:b="Array";break;case RegExp().constructor:b="RegExp";break;case (new Date).constructor:b="Date";break;case Function:b="Function";break;default:var c=a.constructor.toString().match(/function\s*([^( ]+)\(/);
c&&(b=c[1])}break}}catch(d){}finally{b=b.substr(0,1).toUpperCase()+b.substr(1)}return b}function B(a){var b;try{b="\x3c"+String(a)+"\x3e"}catch(c){b="\x3ctoString failed: "+c.message+"\x3e"}null!==a&&void 0!==a&&(b+=" ("+A(a)+")");return b}function D(a){F("Call to fail()",a)}function G(a,b){return b.length==a+1?b[0]:null}function H(a,b,c){return c.length==b+1?c[a]:c[a-1]}function I(a,b){J(null,b.length==a||b.length==a+1&&n(b[0]),"Incorrect arguments passed to assert function")}
function J(a,b,c){b||F(a,c)}
function L(a,b){var c="Expected "+B(a)+" but was "+B(b);if("string"==typeof a&&"string"==typeof b){for(var d=Math.min(a.length,b.length),e=0;e<d&&a.charAt(e)==b.charAt(e);)e++;for(var g=0;g<d&&a.charAt(a.length-g-1)==b.charAt(b.length-g-1);)g++;e+g>d&&(g=0);if(2<e||2<g)d=function(a){var b=Math.max(0,e-2),c=Math.min(a.length,a.length-(g-2));return(0<b?"...":"")+a.substring(b,c)+(c<a.length?"...":"")},c+="\nDifference was at position "+e+". Expected ["+d(a)+"] vs. actual ["+d(b)+"]"}return c}
function M(a,b){I(1,arguments);var c=G(1,arguments),d=H(1,1,arguments);J(c,"boolean"==typeof d,"Bad argument to assert(boolean)");J(c,d,"Call to assert(boolean) with false")}function ua(a,b){I(1,arguments);var c=G(1,arguments),d=H(1,1,arguments);J(c,"boolean"==typeof d,"Bad argument to assertTrue(boolean)");J(c,d,"Call to assertTrue(boolean) with false")}function N(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments);J(G(2,arguments),d===e,L(d,e))}
function va(a,b){I(1,arguments);J(G(1,arguments),null!==H(1,1,arguments),"Expected not to be "+B(null))}function wa(a,b){I(1,arguments);J(G(1,arguments),void 0!==H(1,1,arguments),"Expected not to be "+B(void 0))}var O=null,P="";
function Q(a,b,c){function d(a,b,c){for(var w=0;w<g.length;++w){var K=g[w]===a,C=h[w]===b;if(K||C){K&&C||e.push("Asymmetric cycle detected at "+c);return}}g.push(a);h.push(b);if(a!==b)if(w=A(a),K=A(b),w==K){var C="Array"==w,E=r(w,a,b);if(E!=O)E!=P&&e.push(c+": "+E);else if(C&&a.length!=b.length)e.push(c+": Expected "+a.length+"-element array but got a "+b.length+"-element array");else if(E=c+(C?"[%s]":c?".%s":"%s"),a.__iterator__)"function"==m(a.Ca)?a.Ca(b)||e.push("equals() returned false for "+
(c||w)):a.ja?d(a.ja,b.ja,E.replace("%s","map_")):e.push("unable to check "+(c||w)+" for equality: it has an iterator we do not know how to handle. please add an equals method");else{for(var s in a)C&&(s|0)==s||(s in b?d(a[s],b[s],E.replace("%s",s)):e.push("property "+s+" not present in actual "+(c||K)));for(s in b)C&&(s|0)==s||s in a||e.push("property "+s+" not present in expected "+(c||w));if(C)for(s=0;s<a.length;s++)d(a[s],b[s],E.replace("%s",String(s)))}}else e.push(c+" "+L(a,b));g.pop();h.pop()}
var e=[],g=[],h=[],r=c||function(a,b,c){return(a=ra[a])?a(b,c)?P:L(b,c):O};d(a,b,"");return 0==e.length?null:L(a,b)+"\n   "+e.join("\n   ")}function xa(a,b,c){I(2,arguments);var d=G(2,arguments)?G(2,arguments):"",e=Q(H(1,2,arguments),H(2,2,arguments));J(d,!e,e)}function ya(a,b,c,d){I(3,arguments);var e=H(1,3,arguments),g=H(2,3,arguments),h=H(3,3,arguments);J(G(3,arguments),sa(e,g,h),"Expected "+e+", but got "+g+" which was more than "+h+" away")}
function R(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b}function S(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1}function za(a){var b=document.createElement("DIV");b.innerHTML=a;return b.innerHTML.replace(/^\s+|\s+$/g,"")}function F(a,b){l.CLOSURE_INSPECTOR___&&l.CLOSURE_INSPECTOR___.supportsJSUnit&&l.CLOSURE_INSPECTOR___.jsUnitFailure(a,b);throw new T(a,b);}
function T(a,b){this.Ra=!0;this.message=(a?a:"")+(a&&b?"\n":"")+(b?b:"");var c=pa();if(c)if("array"==m(c)){for(var d=[],e=0;e<c.length;e++){var g=c[e],h=g.Pa()||"unknown",r=g.Oa(),g=r?r+":"+g.Qa()+":"+g.Na():"unknown";d.push(new v("",h,"","",g))}c=d}else c=oa(c);else c=la();this.Ta=na(c);this.Ma=a||null;this.Sa=b||"";Error.captureStackTrace?Error.captureStackTrace(this,T):this.stack=Error().stack||""}ea(T,Error);T.prototype.toString=f("message");q("fail",D);q("assert",M);
q("assertThrows",function(a,b){I(1,arguments);var c=H(1,1,arguments),d=G(1,arguments);J(d,"function"==typeof c,"Argument passed to assertThrows is not a function");try{c()}catch(e){return e&&(n(e.stacktrace)&&n(e.message))&&(c=e.message.length-e.stacktrace.length,e.message.indexOf(e.stacktrace,c)==c&&(e.message=e.message.substr(0,c-14))),e}F(d,"No exception thrown from function passed to assertThrows")});
q("assertNotThrows",function(a,b){I(1,arguments);var c=G(1,arguments),d=H(1,1,arguments);J(c,"function"==typeof d,"Argument passed to assertNotThrows is not a function");try{return d()}catch(e){c=(c?c+"\n":"")+"A non expected exception was thrown from function passed to assertNotThrows",F(c,e.stack||e.stacktrace||e.toString())}});q("assertTrue",ua);
q("assertFalse",function(a,b){I(1,arguments);var c=G(1,arguments),d=H(1,1,arguments);J(c,"boolean"==typeof d,"Bad argument to assertFalse(boolean)");J(c,!d,"Call to assertFalse(boolean) with true")});q("assertEquals",N);q("assertNotEquals",function(a,b,c){I(2,arguments);var d=H(2,2,arguments);J(G(2,arguments),H(1,2,arguments)!==d,"Expected not to be "+B(d))});q("assertNull",function(a,b){I(1,arguments);var c=H(1,1,arguments);J(G(1,arguments),null===c,L(null,c))});q("assertNotNull",va);
q("assertUndefined",function(a,b){I(1,arguments);var c=H(1,1,arguments);J(G(1,arguments),void 0===c,L(void 0,c))});q("assertNotUndefined",wa);q("assertNotNullNorUndefined",function(a,b){I(1,arguments);va.apply(null,arguments);wa.apply(null,arguments)});q("assertNonEmptyString",function(a,b){I(1,arguments);var c=H(1,1,arguments);J(G(1,arguments),void 0!==c&&null!==c&&"string"==typeof c&&""!==c,"Expected non-empty string but was "+B(c))});
q("assertNaN",function(a,b){I(1,arguments);J(G(1,arguments),isNaN(H(1,1,arguments)),"Expected NaN")});q("assertNotNaN",function(a,b){I(1,arguments);J(G(1,arguments),!isNaN(H(1,1,arguments)),"Expected not NaN")});q("assertObjectEquals",xa);q("assertObjectRoughlyEquals",function(a,b,c,d){I(3,arguments);var e=H(3,3,arguments),g=G(3,arguments)?G(3,arguments):"",h=Q(H(1,3,arguments),H(2,3,arguments),function(a,b,c){return(a=ta[a])?a(b,c,e)?P:L(b,c)+" which was more than "+e+" away":O});J(g,!h,h)});
q("assertObjectNotEquals",function(a,b,c){I(2,arguments);var d=G(2,arguments)?G(2,arguments):"",e=Q(H(1,2,arguments),H(2,2,arguments));J(d,e,"Objects should not be equal")});q("assertArrayEquals",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments),g=G(2,arguments)?G(2,arguments):"",h=A(d);J(g,"Array"==h,"Expected an array for assertArrayEquals but found a "+h);h=A(e);J(g,"Array"==h,"Expected an array for assertArrayEquals but found a "+h);xa(g,Array.prototype.concat.call(d),Array.prototype.concat.call(e))});
q("assertElementsEquals",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments),g=G(2,arguments)?G(2,arguments):"";if(d){N("length mismatch: "+g,d.length,e.length);for(var h=0;h<d.length;++h)N("mismatch at index "+h+": "+g,d[h],e[h])}else M(g,!e)});
q("assertElementsRoughlyEqual",function(a,b,c,d){I(3,arguments);var e=H(1,3,arguments),g=H(2,3,arguments),h=H(3,3,arguments),r=G(3,arguments)?G(3,arguments):"";if(e){N("length mismatch: "+r,e.length,g.length);for(var t=0;t<e.length;++t)ya(r,e[t],g[t],h)}else M(r,!g)});
q("assertSameElements",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments),g=G(2,arguments);ua("Bad arguments to assertSameElements(opt_message, expected: ArrayLike, actual: ArrayLike)",ba(d)&&ba(e));d=R(d);e=R(e);J(g,d.length==e.length,"Expected "+d.length+" elements: ["+d+"], got "+e.length+" elements: ["+e+"]");for(var h=R(d),r=0;r<e.length;r++){var t=S(h,e[r]);J(g,-1!=t,"Expected ["+d+"], got ["+e+"]");h.splice(t,1)}});
q("assertEvaluatesToTrue",function(a,b){I(1,arguments);H(1,1,arguments)||J(G(1,arguments),!1,"Expected to evaluate to true")});q("assertEvaluatesToFalse",function(a,b){I(1,arguments);H(1,1,arguments)&&J(G(1,arguments),!1,"Expected to evaluate to false")});q("assertHTMLEquals",function(a,b,c){I(2,arguments);var d=H(2,2,arguments),e=za(H(1,2,arguments)),d=za(d);J(G(2,arguments),e===d,L(e,d))});
q("assertHashEquals",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments),g=G(2,arguments),h;for(h in d)J(g,h in e,"Expected hash had key "+h+" that was not found"),J(g,d[h]==e[h],"Value for key "+h+" mismatch - expected \x3d "+d[h]+", actual \x3d "+e[h]);for(h in e)J(g,h in d,"Actual hash had key "+h+" that was not expected")});q("assertRoughlyEquals",ya);
q("assertContains",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments);J(G(2,arguments),-1!=S(e,d),"Expected '"+e+"' to contain '"+d+"'")});q("assertNotContains",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments);J(G(2,arguments),-1==S(e,d),"Expected '"+e+"' not to contain '"+d+"'")});
q("assertRegExp",function(a,b,c){I(2,arguments);var d=H(1,2,arguments),e=H(2,2,arguments);"string"==typeof d&&(d=RegExp(d));J(G(2,arguments),d.test(e),"Expected '"+e+"' to match RegExp "+d.toString())});function U(a){this.d=a||"Untitled Test Case";this.m=[];this.j=null;a="";l.location&&(a=l.location.search);var b=a.match(/(?:\?|&)runTests=([^?&]+)/i);if(b){this.j={};for(var b=b[1].split(","),c=0,d=b.length;c<d;c++)this.j[b[c]]=1}if(a=a.match(/(?:\?|&)order=(natural|random|sorted)/i))this.la=a[1];this.a=new V(this)}U.prototype.getName=f("d");U.prototype.la="sorted";var Aa=l.setTimeout,Ba=l.clearTimeout,Ca=Date,Da=String(l.setTimeout),Ea=null,Fa="undefined"==typeof opera&&!!l.navigator&&-1!=l.navigator.userAgent.indexOf("MSIE");
k=U.prototype;k.ga=!1;k.i=!1;k.na=0;k.t=0;k.w=0;k.G=null;k.add=function(a){if(this.ga)throw Error("Tests cannot be added after execute() has been called. Test: "+a.name);this.m.push(a)};k.next=function(){for(var a;a=this.m[this.w++];)if(!this.j||this.j[a.name]||this.j[this.w-1])return a;return null};k.reset=function(){this.w=0;this.a=new V(this)};k.ma=function(){return!0};
k.execute=function(){this.ga=!0;this.reset();this.na=this.now();this.i=!0;this.a.N=this.m.length;this.ma()?(this.log("Starting tests: "+this.d),this.R()):(this.log("shouldRunTests() returned false, skipping these tests."),this.a.ra=!0,this.o())};
k.o=function(){W(this,"Done");this.pa();var a=Aa==l.setTimeout&&Ba==l.clearTimeout;!a&&(Fa&&String(l.setTimeout)==Da)&&(a=!0);a||(W(this,"ERROR: Test did not restore setTimeout and clearTimeout"),this.a.c.push(new Ga(this.d,"ERROR: Test did not restore setTimeout and clearTimeout")));l.clearTimeout=Ba;l.setTimeout=Aa;this.Ba=this.now();this.i=!1;this.a.L=this.Ba-this.na;for(var a=document.getElementsByTagName("script"),b=0,c=0,d=a.length;c<d;c++)a[c].src&&b++;this.a.aa=b;this.a.complete=!0;this.log(Ha(this.a));
this.a.h()?this.log("Tests complete"):this.log("Tests Failed");this.G&&(a=this.G,a(),this.G=null)};function W(a,b){a.a.ka.push(Ia()+"  "+b)}k.log=function(a){var b=l.top;b&&"undefined"!=typeof b._allTests||!l.console||("string"==typeof a&&(a=Ia()+" : "+a),a instanceof Error&&a.stack?l.console.log(a,a.message,a.stack):l.console.log(a))};k.h=function(){return!!this.a&&this.a.h()};
k.B=function(a){var b=[];if(this.i)b.push(this.d+" [RUNNING]");else{var c=this.a.h()?"PASSED":"FAILED";b.push(this.d+" ["+c+"]")}l.location&&(c=l.location.href,b.push(c.substring(c.indexOf("google3")+8)));b.push(Ha(this.a));a?b.push(".",this.a.ka.join("\n")):this.a.h()||b.push(this.a.c.join("\n"));b.push(" ");return b.join("\n")};k.W=function(){return this.a.L};k.V=function(){return this.a.aa};k.X=function(){return this.a.l};k.da=function(){try{this.fa()}catch(a){this.T=a}this.execute()};
function Ja(a,b){switch(a.la){case "random":for(var c=b.length;1<c;){var d=Math.floor(Math.random()*c);c--;var e=b[c];b[c]=b[d];b[d]=e}break;case "sorted":b.sort(function(a,b){return a.name==b.name?0:a.name<b.name?-1:1})}}k.fa=function(){};k.pa=function(){};k.ea=function(){};k.s=function(){};function Ka(a,b){a.t=b}
function La(a){var b;b="undefined"!=typeof l.RuntimeObject?l.RuntimeObject("test*"):l;var c=[],d;for(d in b){try{var e=b[d]}catch(g){}/^test/.test(d)&&"function"==m(e)&&c.push(new Ma(d,e,l))}Ja(a,c);for(b=0;b<c.length;b++)a.add(c[b]);a.log(a.m.length+" tests auto-discovered");l.setUp&&(a.ea=p(l.setUp,l));l.tearDown&&(a.s=p(l.tearDown,l));l.setUpPage&&(a.fa=p(l.setUpPage,l));l.tearDownPage&&(a.pa=p(l.tearDownPage,l));l.runTests&&(a.da=p(l.runTests,l));l.shouldRunTests&&(a.ma=p(l.shouldRunTests,l))}
function Na(a,b){return a.T?(b.name="setUpPage for "+b.name,Oa(a,b,a.T),!0):!1}k.R=function(){W(this,"Start");this.t=this.now();for(var a;(a=this.next())&&this.i;){this.a.K++;var b=!1;try{this.log("Running test: "+a.name),Na(this,a)?b=!0:(Ea=a.name,this.ea(),a.execute(),this.s(),Ea=null,b=!0,Pa(this,a))}catch(c){if(Oa(this,a,c),!b)try{this.s()}catch(d){}}if(this.w<this.m.length&&200<this.now()-this.t){W(this,"Breaking async");this.timeout(p(this.R,this),0);return}}this.o()};
k.timeout=function(a,b){return Aa(a,b)};k.clearTimeout=function(a){Ba(a)};k.now=function(){return(new Ca).getTime()};function Ia(){var a=new Ca,b="00"+a.getMilliseconds(),b=b.substr(b.length-3);return(10>a.getHours()?"0"+a.getHours():String(a.getHours()))+":"+(10>a.getMinutes()?"0"+a.getMinutes():String(a.getMinutes()))+":"+(10>a.getSeconds()?"0"+a.getSeconds():String(a.getSeconds()))+"."+b}function Pa(a,b){a.a.M++;b.name in a.a.l||(a.a.l[b.name]=[]);var c=b.name+" : PASSED";W(a,c);a.log(c)}
function Oa(a,b,c){var d=b.name+" : FAILED";a.log(d);W(a,d);c=a.k(b.name,c);a.a.c.push(c);b.name in a.a.l?a.a.l[b.name].push(c.toString()):a.a.l[b.name]=[c.toString()]}k.k=function(a,b){var c=null,d=null;b?(this.log(b),n(b)?c=b:(c=b.message||b.description||b.toString(),b.stack?(d=oa(b.stack),d=na(d)):d=b.stackTrace)):c="An unknown error occurred";c=new Ga(a,c,d);b&&b.isJsUnitException&&b.loggedJsUnitException||W(this,c.toString());b&&b.isJsUnitException&&(b.loggedJsUnitException=!0);return c};
function Ma(a,b,c){this.name=a;this.Ha=b;this.scope=c||null}Ma.prototype.execute=function(){this.Ha.call(this.scope)};function V(a){this.qa=a;this.aa=this.L=this.M=this.K=this.N=0;this.ra=!1;this.l={};this.c=[];this.ka=[];this.complete=!1}V.prototype.h=function(){return this.complete&&0==this.c.length};
function Ha(a){var b=a.K+" of "+a.N+" tests run in "+a.L+"ms.\n";if(a.ra)b+="Tests not run because shouldRunTests() returned false.";else{var c=a.N-a.M,d="",e;if(a.qa.j){e=a.qa.j;var g=0,h;for(h in e)g++;e=g}else e=0;e&&(c=e-a.M,d=", "+(a.N-e)+" suppressed by querystring");b+=a.M+" passed, "+c+" failed"+d+".\n"+Math.round(a.L/a.K)+" ms/test. "+a.aa+" files loaded."}return b}function Ga(a,b,c){this.source=a;this.message=b;this.stack=c||null}
Ga.prototype.toString=function(){return"ERROR in "+this.source+"\n"+this.message+(this.stack?"\n"+this.stack:"")};function Qa(){this.c=[]}k=Qa.prototype;k.b=null;k.C=!1;k.D=null;k.S=null;k.oa=!0;k.ia=function(a){if(this.b&&this.b.i)throw Error("The test runner is already waiting for a test to complete");this.b=a;this.C=!0};k.Ia=function(a){this.oa=a};k.Ea=f("C");k.Da=function(){return 0<this.c.length||this.C&&!!this.b&&this.b.ga&&!this.b.i};k.h=function(){return!(0<this.c.length)&&!!this.b&&this.b.h()};k.k=function(a){this.S&&!this.S.call(null,a)||this.c.push(a)};
k.Fa=function(a){var b=Ea;if(this.b)this.b.k(b,a);else throw Error("Test runner not initialized with a test case. Original exception: "+a.message);};k.B=function(a){var b=[];this.b&&b.push(this.b.B(a));0<this.c.length&&(b.push("JavaScript errors detected by test runner:"),b.push.apply(b,this.c),b.push("\n"));return b.join("\n")};k.W=function(){return this.b?this.b.W():0};k.V=function(){return this.b?this.b.V():0};
k.execute=function(){if(!this.b)throw Error("The test runner must be initialized with a test case before execute can be called.");if(this.oa&&0==this.b.m.length)throw Error("No tests found in given test case: "+this.b.getName()+" By default, the test runner fails if a test case has no tests. To modify this behavior, see goog.testing.TestRunner's setStrict() method, or G_testRunner.setStrict()");var a=p(this.Ga,this);this.b.G=a;this.b.da()};
k.Ga=function(){var a=this.b.B(!0);0<this.c.length&&(a+="\n"+this.c.join("\n"));if(!this.D){var b=document.getElementById("closureTestRunnerLog");null==b&&(b=document.createElement("div"),document.body.appendChild(b));this.D=b}Ra(this,a);a=document.createElement("a");a.style.display="block";a.style.fontSize="small";a.href="";a.onclick=p(function(){this.execute();return!1},this);a.innerHTML="Run again without reloading";this.D.appendChild(a)};
function Ra(a,b){for(var c=b.split("\n"),d=0;d<c.length;d++){var e=c[d],g,h=/FAILED/.test(e)||/ERROR/.test(e);g=/PASSED/.test(e)?"darkgreen":h?"darkred":"#333";var r=document.createElement("div");"\x3e "==e.substr(0,2)?r.innerHTML=e:r.appendChild(document.createTextNode(e));if(h&&(e=/(\S+) (\[[^\]]*] )?: (FAILED|ERROR)/.exec(e))){var e="runTests\x3d"+e[1],t=window.location.search;if(t)var y=/runTests=([^&]*)/.exec(t),e=y?t.substr(0,y.index)+e+t.substr(y.index+y[0].length):t+"\x26"+e;else e="?"+e;
t=window.location.href;(y=window.location.hash)&&"#"!=y.charAt(0)&&(y="#"+y);t=t.split("#")[0].split("?")[0]+e+y;e=document.createElement("A");e.innerHTML="(run individually)";e.style.fontSize="0.8em";e.href=t;r.appendChild(document.createTextNode(" "));r.appendChild(e)}r.style.color=g;r.style.font="normal 100% monospace";0==d&&(r.style.padding="20px",r.style.marginBottom="10px",h?(r.style.border="5px solid "+g,r.style.backgroundColor="#ffeeee"):(r.style.border="1px solid black",r.style.backgroundColor=
"#eeffee"));try{r.style.whiteSpace="pre-wrap"}catch($a){}2>d&&(r.style.fontWeight="bold");a.D.appendChild(r)}}k.log=function(a){this.b&&this.b.log(a)};k.X=function(){return this.b?this.b.X():null};(function(){Error.stackTraceLimit=50;var a=window.setTimeout;if(top.JsUnitTestManager||top.jsUnitTestManager)document.write('\x3cscript type\x3d"text/javascript" src\x3d"../../third_party/java/jsunit/core/app/jsUnitCore.js"\x3e\x3c/script\x3e');else{var b=new Qa;q("G_testRunner",b);q("G_testRunner.initialize",b.ia);q("G_testRunner.isInitialized",b.Ea);q("G_testRunner.isFinished",b.Da);q("G_testRunner.isSuccess",b.h);q("G_testRunner.getReport",b.B);q("G_testRunner.getRunTime",b.W);q("G_testRunner.getNumFilesLoaded",
b.V);q("G_testRunner.setStrict",b.Ia);q("G_testRunner.logTestFailure",b.Fa);q("G_testRunner.getTestResults",b.X);l.debug||q("debug",p(b.log,b));l.G_errorFilter&&(b.S=l.G_errorFilter);var c=window.onerror;window.onerror=function(a,d,h){c&&c(a,d,h);"object"==typeof a?a.target&&"SCRIPT"==a.target.tagName?b.k("UNKNOWN ERROR: Script "+a.target.src):b.k("UNKNOWN ERROR: No error information available."):b.k("JS ERROR: "+a+"\nURL: "+d+"\nLine: "+h)};var d=window.onload;window.onload=function(c){d&&d(c);a(function(){if(!b.C){var a=
new U(document.title);La(a);b.ia(a)}b.execute()},500);window.onload=null}}})();function X(a){U.call(this,a)}ea(X,U);function Sa(a){this.message=a||""}Sa.prototype.Z=!0;Sa.prototype.toString=function(){return"[AsyncTestCase.ControlBreakingException]"};k=X.prototype;k.ha=1E3;k.Ka=500;k.Aa=!1;k.n="";k.$="";k.g=0;k.u=!1;k.Y=!1;k.p=!0;k.U=0;k.ca=0;k.J=!1;k.f=0;function Ta(a){a.p||(a.p=!0,Ua(a),a.timeout(p(a.r,a,null),0))}
function Y(a,b){if(b&&b.Z)throw b;Ua(a);var c=new Ma(a.n,aa);a.e&&(c.name=a.e.name+" ["+c.name+"]");a.e?Oa(a,c,b):a.T=b;a.timeout(p(a.r,a,a.ua),a.Ka);a.J||(a.f+=1,Z(a,"doAsynError: numControlExceptionsExpected_ \x3d "+a.f+" and throwing exception."));c="";"string"==typeof b?c=b:b&&b.message&&(c=b.message);throw new Sa(c);}k.da=function(){Va(this);Wa(this);$(this,this.xa,"setUpPage");this.r()};k.R=function(){W(this,"Start");$(this,this.A,"doIteration");this.r()};
k.o=function(){this.I&&(window.onerror=this.I,this.I=null,J=this.H,this.H=null,D=this.ba,this.ba=null);$(this,null,"finalized");X.Ja.o.call(this)};function Z(a,b){a.Aa&&a.log("AsyncTestCase - "+b)}function Xa(a,b){try{Y(a,b)}catch(c){if(c.Z)a.f-=1,Z(a,"doTopOfStackAsyncError_: numControlExceptionsExpected_ \x3d "+a.f+" and catching exception.");else throw c;}}
k.ua=function(){if(this.Y)Ta(this);else{this.p=this.Y=!0;var a=this.F,b="TestCase.execute (after error)";this.e&&(a=this.A,b="doIteration (after error)");$(this,function(){this.Y=!1;$(this,a,b)},"doAsyncError");this.u||(this.u=!0,this.s())}};function Va(a){a.H||(a.H=J,a.ba=D,J=function(){try{a.H.apply(this,arguments)}catch(b){Z(a,"Wrapping failed assert()"),Y(a,b)}},D=function(){try{a.ba.apply(this,arguments)}catch(b){Z(a,"Wrapping fail()"),Y(a,b)}})}
function Wa(a){a.I||(a.I=window.onerror,window.onerror=function(b,c,d){if(-1!=String(b).indexOf("[AsyncTestCase.ControlBreakingException]")&&a.f)return a.f-=1,Z(a,"window.onerror: numControlExceptionsExpected_ \x3d "+a.f+" and ignoring exception. "+b),!0;Z(a,"window.onerror caught exception.");Xa(a,b+"\nURL: "+c+"\nLine: "+d);return!1})}
function Ya(a){!a.g&&0<a.ha&&(a.g=a.timeout(p(function(){Z(this,"Timeout timer fired with id "+this.g);this.g=0;Xa(this,"Timed out while waiting for continueTesting() to be called.")},a,null),a.ha),Z(a,"Started timeout timer with id "+a.g))}function Ua(a){a.g&&(Z(a,"Clearing timeout timer with id "+a.g),a.clearTimeout(a.g),a.g=0)}function $(a,b,c){a.F=b&&p(b,a);a.$=c}
function Za(a,b){try{return b.call(a),{v:!1,message:""}}catch(c){Z(a,"Caught exception in callTopOfStackFunc_");try{return Y(a,c),{v:!1,message:""}}catch(d){if(!d.Z)throw d;return{v:!0,message:d.message}}}}
k.r=function(a){if(this.J)a&&a.call(this);else{Ka(this,this.now());this.J=!0;var b={};for(a&&(b=Za(this,a));this.p&&this.F&&!b.v;)if(this.ta=this.F,this.n=this.$,this.F=null,this.$="",Z(this,"Performing step: "+this.n),b=Za(this,this.ta),200<this.now()-this.t&&!b.v){W(this,"Breaking async");var c=this;this.timeout(function(){c.r()},100);break}this.J=!1}};k.xa=function(){$(this,this.execute,"TestCase.execute");this.fa()};
k.A=function(){this.ca=this.U=0;(this.e=this.next())&&this.i?(this.a.K++,Na(this,this.e)?$(this,this.A,"doIteration"):$(this,this.ya,"setUp")):this.o()};k.ya=function(){this.log("Running test: "+this.e.name);this.u=!1;$(this,this.va,this.e.name);this.ea()};k.va=function(){$(this,this.za,"tearDown");this.e.execute()};k.za=function(){this.u=!0;$(this,this.wa,"doNext");this.s()};k.wa=function(){$(this,this.A,"doIteration");Pa(this,this.e)};window.AsyncTest=function(a){var b=new X(void 0);La(b);var c=l.G_testRunner;if(c)c.initialize(b);else throw Error("G_testRunner is undefined. Please ensure goog.testing.jsunit is included.");this.O=b;"number"==typeof a&&(this.O.ha=a)};window.AsyncTest.prototype.wait=function(a){var b=this.O;b.p=!1;b.n=a||b.n;Ua(b);Ya(b)};window.AsyncTest.prototype.next=function(){var a=this.O;if(a.ca<a.U)throw Error("Still waiting for "+(a.U-a.ca)+" signals.");Ta(a)};})();
